apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: telegram
  namespace: flux-system
spec:
  type: telegram
  channel: "-651852800" # or "-1557265138" (channel id)
  secretRef:
    name: telegram-token
