---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
spec:
  releaseName: reloader
  chart:
    spec:
      chart: reloader
      version: v0.0.114
      sourceRef:
        kind: HelmRepository
        name: reloader
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
