---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
spec:
  interval: 30m
  url: https://charts.jetstack.io
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: reloader
spec:
  interval: 30m
  url: https://stakater.github.io/stakater-charts
